### ISSUE TITLE
Can't build the document

### ISSUE THREAD

**Issue by grinnellm** [cgrandin/csas-latex#42]
I get an error when I try to compile the PDF (RStudio):
`Quitting from lines NA-488  (./maindoc/3_modelling.rnw)`
I get the new q-priors runs, and ran `delete.rdata.files()` and `build()`, but no luck.

**Comment by cgrandin** [comment]
I'm working on it. It's going to take a long time to debug this as the build process takes so long

**Comment by cgrandin** [comment]
There was a quote mark that was somehow deleted in the figures section so I've fixed that but there is another error in the introduction.

Anytime I write latex sections, I always comment out all the other sections in res-doc.rnw so that I can test it more quickly.

**Comment by jaclyncleary** [comment]
I can get the pdf to compile from RStudio with q-prior runs.

I ran fresh.batch first, then library(knitr);knit('./res-doc.rnw'), then the rest.

**Comment by grinnellm** [comment]
Nice. I'll give it a shot. Are the citations coming in too?

**Comment by jaclyncleary** [comment]
no citations coming in :(

and I just deleted my comment because I've got M-sensitivities but not q-prior ones - but enough to keep working on the text!

**Comment by cgrandin** [comment]
It appears that we can't use \cite{} in Miktex but you can on the mac. So I've changed all of them to \citet{} and am building now. There was a bunch of them in the introduction.

Hopefully that was all. Then I'll get back to doing the q sensitivity plots

**Comment by grinnellm** [comment]
Did you source "ResearchDocumentV2.R" after copying the q-prior sensitivities, to put the *.csv's in the /mcmc? Then `build()`.

**Comment by cgrandin** [comment]
I did, yes

**Comment by grinnellm** [comment]
Oops, I meant Jaclyn.

**Comment by jaclyncleary** [comment]
@cgrandin 
I just merged with you- what was the error in the intro I was making, so that I don't make it again?

**Comment by cgrandin** [comment]
Use \citet instead of \cite

**Comment by cgrandin** [comment]
But I haven't pushed the changes yet, and it's still breaking somewhere else

**Comment by jaclyncleary** [comment]
ok

**Comment by cgrandin** [comment]
Ok, it's all fixed in commit f5a0ca2a51d2f3730d7dd3f03459132af7c870cc.

I guess we can't have the >% operator inside an \Sexpr{}. That also broke it.

**Comment by grinnellm** [comment]
Ah, dang it -- did I mess it up?
I fetched and merged, and then fixed some merge conflicts in the intro. Now I get this error when I try to compile:
`Error in readLines(if (is.character(input2)) { :`
I ran `delete.rdata.files()` and `build()` but I still get the same error.

**Comment by Shawkshaw** [comment]
I was getting this error before I merged with you...I think?

**Comment by cgrandin** [comment]
Do you have it working now Matt?

**Comment by grinnellm** [comment]
Took me a while to get up to date and fix the merge conflicts. I think we're all working on the same sections. No, still the same error.

**Comment by jaclyncleary** [comment]
Although last night I was able to build the pdf, I can't now.

When I run, library(knitr);knit('./res-doc.rnw') I get:
Quitting from lines 113-113 (./maindoc/test.rnw) 
Error in readLines(if (is.character(input2)) { : 
  cannot open the connection
In addition: Warning message:
In readLines(if (is.character(input2)) { :
  cannot open file './maindoc/test.rnw': No such file or directory

And when I compile PDF from res-doc.rnw, I get:
Line 113: Error in readLines(if (is.character(input2)) { :

(this is all after running fresh.sh)

**Comment by grinnellm** [comment]
What is maindoc/test.rnw? I don't have that file either.

**Comment by cgrandin** [comment]
test.rnw is a file I have locally, I use it to put plot or table code in, then I comment out every other section so that it builds really quick. It's just a way of making sure I haven't broken anything before I put the code in the document. It should have been commented out when I committed but if it wasn't my apologies.

I'm trying again now, and will debug again. So far today has been basically a debug session. I'm staying later today also.

**Comment by cgrandin** [comment]
There were more /cite{} commands in the intro that I had to change to /citet{} again. The doc builds for me on commit 911bd78b12a0b6e28f9ee0e64cc2232f24b7dae6

**Comment by jaclyncleary** [comment]
so if I fetch from you I should be good?

**Comment by cgrandin** [comment]
Should be!

**Comment by grinnellm** [comment]
Thanks Chris. I just found and fixed an error in all.bib (my bad) -- fetch from me to make the refs work.
